"""Persistent classrooms, two independent high-entropy join codes, and the
ClassSession lifecycle (start/end a class, one ACTIVE session at a time)."""

from backend.classrooms.service import (
    ClassroomError,
    ClassroomView,
    JoinClosed,
    NoActiveSession,
    NotCoFacultyEligible,
    NotEnrolled,
    SessionAlreadyActive,
    WrongCodeRole,
    archive_classroom,
    can_act_as_faculty,
    create_classroom,
    demote_all_class_faculty,
    demote_class_faculty_to_student,
    end_session,
    faculty_roster_with_users,
    generate_join_code,
    get_active_session,
    has_any_faculty_membership,
    join_classroom,
    promote_student_to_class_faculty,
    regenerate_join_code,
    remove_faculty,
    rename_classroom,
    require_active_session,
    restore_classroom,
    roster_with_users,
    set_join_open,
    start_session,
    student_count,
)

__all__ = [
    "ClassroomError",
    "ClassroomView",
    "JoinClosed",
    "NoActiveSession",
    "NotCoFacultyEligible",
    "NotEnrolled",
    "SessionAlreadyActive",
    "WrongCodeRole",
    "can_act_as_faculty",
    "create_classroom",
    "demote_class_faculty_to_student",
    "end_session",
    "faculty_roster_with_users",
    "generate_join_code",
    "get_active_session",
    "has_any_faculty_membership",
    "join_classroom",
    "promote_student_to_class_faculty",
    "regenerate_join_code",
    "remove_faculty",
    "require_active_session",
    "roster_with_users",
    "set_join_open",
    "start_session",
    "student_count",
]
