"""Experiment 7 knowledge model: concept graph, step -> why -> concept links,
misconceptions and Socratic questions.

Authority: the IACHY102 manual's Experiment 7 section and
knowledge/adjacent/exp07_background.md (its "Common misunderstandings"
paragraph seeds the misconceptions). No numeric reference values appear
here -- the walkthrough deliberately withholds HOMO/LUMO values, and so does
this model. Step ids match backend/socratic_engine/walkthrough/exp07_script.
"""

from __future__ import annotations

from .types import Concept, ConceptQuestion, Misconception, StepKnowledge, build

C = Concept

CONCEPTS = (
    C("molecular_structure", "Molecular structure",
      "Which atoms are present and how they are bonded, before any calculation.", (), 1,
      "You build methane and O2 as the starting structures."),
    C("molecular_geometry", "Molecular geometry",
      "The 3-D arrangement of the atoms: bond lengths and bond angles.",
      ("molecular_structure",), 2, "Methane is drawn as a tetrahedral arrangement."),
    C("atomic_orbitals", "Atomic orbitals",
      "The s, p, d and f regions in which an atom's electrons are found.", (), 2,
      "The shell table at the end counts electrons by s, p, d and f type."),
    C("molecular_orbitals", "Molecular orbitals",
      "Orbitals spread over the whole molecule, formed by combining atomic orbitals; each holds up to two electrons.",
      ("atomic_orbitals",), 3, "Avogadro draws the molecular orbitals ORCA computed."),
    C("hybridization", "Hybridization",
      "Mixing of atomic orbitals on one atom to describe bonds that point in the geometry the molecule actually has.",
      ("atomic_orbitals", "molecular_geometry"), 1,
      "Connects the tetrahedral methane geometry to its bonding orbitals."),
    C("molecular_energy", "Molecular energy",
      "The total energy ORCA computes for a given arrangement of the nuclei and electrons.",
      ("molecular_structure",), 2, "Each run reports a final single-point energy."),
    C("geometry_optimization", "Geometry optimization",
      "Adjusting the atom positions step by step to lower the calculated total energy until it stops decreasing.",
      ("molecular_geometry", "molecular_energy"), 3,
      "The first ORCA job is an optimisation; its energy falls cycle by cycle."),
    C("optimized_geometry", "Optimized geometry",
      "The arrangement the optimisation ends on: the lowest-energy structure for that method and basis set.",
      ("geometry_optimization",), 3, "Later calculations start from this structure."),
    C("electronic_structure", "Electronic structure",
      "How the electrons are distributed over the molecular orbitals, including charge and spin.",
      ("molecular_orbitals",), 2, "Charge and multiplicity must match the electron count (O2 is the test)."),
    C("homo", "HOMO",
      "The highest occupied molecular orbital: the occupied orbital with the highest energy.",
      ("molecular_orbitals", "electronic_structure"), 3, "You read and draw the HOMO."),
    C("lumo", "LUMO",
      "The lowest unoccupied molecular orbital: the empty orbital with the lowest energy.",
      ("molecular_orbitals", "electronic_structure"), 3, "You read and draw the LUMO."),
    C("dft", "DFT",
      "A way of approximating the electronic energy from the electron density rather than the full wavefunction.",
      ("electronic_structure",), 2, "The method you pick in the ORCA dialog."),
    C("functional", "Computational functional / method",
      "The specific approximation used within a method; different ones give slightly different energies.",
      ("dft",), 2, "Tables 1 and 2 compare several methods."),
    C("basis_set", "Basis set",
      "The set of mathematical functions used to describe the orbitals; a larger set describes them more flexibly, but it is still the same molecule.",
      ("atomic_orbitals",), 3, "Tables 1 and 2 compare several basis sets."),
    C("single_point", "Single-point calculation",
      "One energy and orbital calculation at a fixed geometry, with no atom movement.",
      ("molecular_energy", "optimized_geometry"), 2, "Orbital energies come from a single point on the optimised structure."),
    C("orbital_contribution", "Orbital contribution",
      "How much each type of atomic orbital (s, p, d, f) contributes to the molecule's occupied orbitals.",
      ("atomic_orbitals", "molecular_orbitals"), 2, "Table 2 counts electrons by s, p, d and f type."),
    C("method_comparison", "Comparison of computational methods",
      "Repeating the same molecule with different methods and basis sets to see which results depend on the approximation.",
      ("functional", "basis_set", "single_point"), 3, "The 12-run method/basis comparison."),
    C("interpreting_results", "Interpreting your results",
      "Reading a pattern in your own numbers across runs: what changes, what stays similar, and how big the change is compared with the value.",
      ("method_comparison", "homo", "lumo"), 3,
      "After six runs of methane you can see how far method and basis set move the HOMO and LUMO."),
)

MISCONCEPTIONS = (
    Misconception(
        "opt_is_cosmetic", "geometry_optimization",
        "Optimization just makes the molecule look nicer or tidier.",
        (r"\b(look|looks|looking)\s+(nicer|better|prettier|neater|cleaner)",
         r"\b(pretty|prettier|tidy|tidier|neat|neater|cosmetic|aesthetic)",
         r"\bmake[s]?\s+(it|the molecule|the structure)\s+(look|nicer|better)"),
        "What quantity is ORCA actually trying to make smaller as it moves the atoms?",
        "The optimisation moves the atoms to lower the calculated total energy; the tidier shape is a by-product."),
    Misconception(
        "homo_most_electrons", "homo",
        "The HOMO is the orbital with the most electrons.",
        (r"homo.{0,40}(most|maximum|max|largest)\s+(number\s+of\s+)?electrons",
         r"most\s+(number\s+of\s+)?electrons.{0,40}homo",
         r"highest\s+(number|amount)\s+of\s+electrons"),
        "In 'highest occupied', what is the 'highest' referring to: the orbital's energy or how many electrons it holds?",
        "'Highest' refers to energy: the HOMO is the occupied orbital at the highest energy. An orbital holds at most two electrons."),
    Misconception(
        "basis_is_new_molecule", "basis_set",
        "Different basis sets are different molecules.",
        (r"basis\s+sets?.{0,50}(different|new|another)\s+(molecule|compound|structure)",
         r"(different|new|another)\s+(molecule|compound).{0,30}basis"),
        "Are we changing the molecule itself, or changing how we describe it mathematically in the calculation?",
        "The molecule is the same; the basis set only changes how well the calculation can describe its orbitals."),
    Misconception(
        "neg_energy_unstable", "molecular_energy",
        "A negative energy means the molecule is unstable.",
        (r"negative.{0,40}(unstable|bad|wrong|not\s+stable)",
         r"(unstable|bad).{0,30}negative"),
        "Total energies are measured from a reference where the separated nuclei and electrons are far apart. What would a lower number mean, then?",
        "A negative total energy is normal. A lower (more negative) energy means a more strongly bound, more stable arrangement."),
    Misconception(
        "methods_must_agree", "method_comparison",
        "Different methods should give exactly the same answer, so any difference means a mistake.",
        (r"(should|must|supposed\s+to)\s+(all\s+)?(be\s+)?(the\s+)?same",
         r"(difference|different).{0,40}(mistake|error|wrong)\b"),
        "Each method approximates the electronic problem in a different way. Would you expect different approximations to agree to every digit?",
        "Different methods and basis sets are different approximations, so small differences in calculated values are expected."),
)

Q = ConceptQuestion

QUESTIONS = (
    Q("q_opt_predict", "geometry_optimization", "PREDICTION",
      "Before we optimise: do you expect the structure you drew to already be the lowest-energy one? Why or why not?",
      groups=((r"\bno\b", r"\bnot\b", r"won'?t", r"unlikely", r"probably\s+not", r"approximate", r"rough", r"guess", r"drawn", r"may\s+not"),
              (r"energy", r"lowest", r"minim", r"stable", r"relax")),
      need=2,
      expected_reasoning="The drawn geometry is an approximate guess, so it is not generally the lowest-energy arrangement for the chosen method.",
      scaffold="You placed the atoms by hand. Would hand-placed positions match the exact energy minimum of the calculation?"),
    Q("q_opt_why", "geometry_optimization", "WHY",
      "Why do we optimise the geometry instead of calculating the orbitals straight from the structure we drew?",
      groups=((r"energy", r"lowest", r"minim", r"stable", r"equilibrium"),
              (r"geometr", r"structure", r"positions?", r"bond", r"atoms?"),
              (r"orbital", r"before", r"start", r"accura", r"correct", r"reliable", r"appropriate", r"proper")),
      need=2,
      expected_reasoning="Orbital energies depend on geometry; optimisation lowers the total energy and gives a consistent starting structure.",
      scaffold="The orbital energies depend on where the atoms sit. Which positions is the calculation itself happiest with?"),
    Q("q_opt_observe", "geometry_optimization", "OBSERVATION",
      "Look at the first and last energy in the output. What changed, and in which direction?",
      groups=((r"decreas", r"lower", r"drop", r"fell", r"fall", r"less", r"more\s+negative", r"went\s+down", r"reduc"),),
      need=1,
      expected_reasoning="The total energy decreases over the optimisation cycles.",
      scaffold="Compare the two numbers. Is the last one higher or lower than the first?"),
    Q("q_energy_lower", "molecular_energy", "INTERPRETATION",
      "Your energies are large negative numbers. What does a lower (more negative) total energy tell you about an arrangement of the atoms?",
      groups=((r"stable", r"stabil", r"bound", r"favou?rable", r"tighter", r"strongly"),
              (r"lower", r"more\s+negative", r"decreas", r"negative", r"less\s+energy")),
      need=1,
      expected_reasoning="A lower (more negative) total energy means a more stable, more strongly bound arrangement; a negative value alone is not a sign of instability.",
      scaffold="Think of energy as a cost. Is the arrangement with the lower total energy the one the atoms would rather be in?"),
    Q("q_opt_consequence", "optimized_geometry", "CONSEQUENCE",
      "What could go wrong if we ran the orbital calculation on the structure as drawn instead of the optimised one?",
      groups=((r"wrong", r"inaccura", r"not\s+(be\s+)?(correct|accurate|reliable)", r"differ", r"change", r"shift", r"unreliable", r"incorrect", r"error", r"mislead"),
              (r"energ", r"orbital", r"homo", r"lumo", r"result", r"value")),
      need=2,
      expected_reasoning="Orbital energies computed at a non-minimum geometry are not the values for the relaxed molecule.",
      scaffold="Orbital energies depend on atom positions. If the positions are not the relaxed ones, whose orbital energies are you reading?"),
    Q("q_geom_use_opt", "optimized_geometry", "WHY",
      "Why do we start the next calculation from the optimised geometry rather than the structure we originally drew?",
      groups=((r"optimi[sz]ed", r"lowest", r"minim", r"relaxed", r"equilibrium", r"best"),
              (r"energy", r"geometr", r"structure", r"accura", r"consistent", r"correct")),
      need=2,
      expected_reasoning="The optimised structure is the energy-minimised geometry for the method, so later electronic results correspond to the relaxed molecule.",
      scaffold="Which of the two structures has been adjusted to give the lowest calculated energy?"),
    Q("q_orbital_predict", "molecular_orbitals", "PREDICTION",
      "What do you expect a molecular-orbital picture to show?",
      groups=((r"electron", r"probab", r"density", r"region", r"space", r"where", r"cloud"),),
      need=1,
      expected_reasoning="A molecular orbital describes where an electron in the molecule is likely to be found, spread over the atoms.",
      scaffold="Think about what an orbital describes about an electron, and where in the molecule."),
    Q("q_homo_meaning", "homo", "INTERPRETATION",
      "In your own words, what do HOMO and LUMO stand for, and how do they differ?",
      groups=((r"highest\s+occupied", r"occupied.{0,20}highest", r"\bfilled\b.{0,20}highest"),
              (r"lowest\s+unoccupied", r"unoccupied.{0,20}lowest", r"lowest.{0,20}empty", r"\bempty\b")),
      need=2,
      expected_reasoning="HOMO: highest-energy orbital that holds electrons. LUMO: lowest-energy orbital that is empty.",
      scaffold="Break the names apart: 'highest occupied' and 'lowest unoccupied'. What is each one ranked by?"),
    Q("q_homo_picture", "homo", "INTERPRETATION",
      "What do the coloured lobes in the orbital picture represent?",
      groups=((r"electron", r"probab", r"density", r"region", r"where", r"space"),
              (r"phase", r"sign", r"positive", r"negative", r"colou?r", r"lobe", r"orbital")),
      need=1,
      expected_reasoning="The lobes show where the orbital has amplitude (where an electron in it is likely to be found); the two colours are the opposite signs/phases of the orbital.",
      scaffold="The surface marks where the orbital has appreciable amplitude. What does that say about where its electrons are likely to be?"),
    Q("q_electronic_o2", "electronic_structure", "WHY",
      "Why does the electron count matter when we set the charge and spin for O2?",
      groups=((r"electron", r"count", r"number"),
              (r"spin", r"multiplicity", r"unpaired", r"paired", r"parity", r"even", r"odd", r"charge")),
      need=2,
      expected_reasoning="Charge and multiplicity must be consistent with the total electron count, since spin is set by how many electrons are unpaired.",
      scaffold="Spin comes from unpaired electrons. What must be consistent between the number of electrons and the spin you choose?"),
    Q("q_method_why", "method_comparison", "WHY",
      "Why are we repeating the same molecule with different methods and basis sets?",
      groups=((r"differ", r"compare", r"vary", r"depend", r"change", r"effect", r"affect"),
              (r"method", r"basis", r"approximat", r"accura", r"result", r"value", r"energ")),
      need=2,
      expected_reasoning="Each method/basis set is a different approximation, so calculated properties can depend on the choice; repeating shows which results are robust.",
      scaffold="Is the molecule changing between runs, or is the way it is approximated changing?"),
    Q("q_basis_same", "basis_set", "WHY",
      "When the basis set changes, is it a different molecule? What is changing instead?",
      groups=((r"same\s+molecule", r"not\s+(a\s+)?(different|new)", r"\bno\b", r"same\s+(structure|atoms)"),
              (r"describe", r"represent", r"function", r"approximat", r"calculat", r"mathemat", r"flexib", r"accura")),
      need=2,
      expected_reasoning="The molecule is unchanged; the basis set changes the mathematical functions used to describe its orbitals.",
      scaffold="The atoms and bonds stay the same. What part of the calculation is being swapped out?"),
    Q("q_pattern_interpret", "interpreting_results", "INTERPRETATION",
      "Looking across your runs, what pattern do you notice, and what stayed roughly similar?",
      groups=((r"similar", r"same", r"close", r"consistent", r"small", r"slight", r"differ", r"trend", r"pattern", r"vary", r"larger", r"bigger"),
              (r"homo", r"lumo", r"energ", r"gap", r"basis", r"method", r"value", r"result")),
      need=2,
      expected_reasoning="Values shift modestly between methods and basis sets while the overall picture (ordering, rough size) stays similar.",
      scaffold="Pick one quantity, such as the HOMO energy, and compare it across two runs. How large is the change compared to the value itself?",
      min_rows=6),
    Q("q_contrib_meaning", "orbital_contribution", "INTERPRETATION",
      "What does the s, p, d and f electron count in Table 2 tell you about the molecule's occupied orbitals?",
      groups=((r"\bs\b", r"\bp\b", r"contribut", r"type", r"character", r"made\s+(up|of)", r"composition", r"mix"),
              (r"atomic\s+orbital", r"orbital", r"electron", r"atom")),
      need=2,
      expected_reasoning="It shows which types of atomic orbital the occupied molecular orbitals are built from.",
      scaffold="Each molecular orbital is built from atomic orbitals. What does the count say about which kinds were used?"),
    Q("q_compare_ch4_o2", "electronic_structure", "OBSERVATION",
      "What did you notice when you compared CH4 and O2?",
      groups=((r"o2", r"oxygen", r"ch4", r"methane"),
              (r"spin", r"unpaired", r"electron", r"homo", r"lumo", r"differ", r"gap", r"orbital", r"energ")),
      need=2,
      expected_reasoning="They differ in electron count/spin state and in orbital energies; O2 needs a non-singlet spin setup.",
      scaffold="Compare something concrete: the spin you had to set, or their HOMO and LUMO values."),
    Q("q_transfer_opt", "geometry_optimization", "TRANSFER",
      "If you were given a different molecule, why would geometry optimization still be useful?",
      groups=((r"energy", r"lowest", r"minim", r"stable", r"equilibrium", r"relax"),
              (r"any", r"every", r"different", r"other", r"general", r"always", r"same\s+reason", r"geometr", r"structure", r"molecule")),
      need=2,
      expected_reasoning="Any hand-drawn geometry is approximate; optimisation finds the lowest-energy structure for the chosen method, whatever the molecule.",
      scaffold="Would a hand-drawn structure of a new molecule be any more exact than the one you drew here?"),
    Q("q_transfer_orbitals", "molecular_orbitals", "TRANSFER",
      "If we changed from CH4 to O2, would you expect the same orbital behaviour? Why?",
      groups=((r"\bno\b", r"\bnot\b", r"differ", r"won'?t", r"unlikely"),
              (r"electron", r"atom", r"bond", r"spin", r"structure", r"orbital", r"unpaired")),
      need=2,
      expected_reasoning="Different atoms, electron counts and bonding mean different orbitals and different HOMO/LUMO; O2 also has unpaired electrons.",
      scaffold="Are the atoms, the number of electrons and the bonding the same in the two molecules?"),
)

_S = StepKnowledge

STEPS = (
    _S("b3_methane",
       why="The calculation needs a starting structure; methane's four hydrogens sit around the carbon in a tetrahedral arrangement.",
       concepts=("molecular_structure", "molecular_geometry"),
       expected_observation="Five atoms: one carbon and four hydrogens."),
    _S("o3_job_scf",
       why="The job type chooses what ORCA does (optimise or single point), and charge and spin must match the electron count.",
       concepts=("geometry_optimization", "electronic_structure"),
       possible_consequence="A charge/spin that does not match the electron count makes the job fail."),
    _S("o4_method_basis",
       why="The method and basis set define the approximation ORCA uses, so they shape the calculated numbers.",
       concepts=("dft", "functional", "basis_set"),
       misconceptions=("basis_is_new_molecule",)),
    _S("r1_run",
       why="The optimisation moves the atoms to lower the calculated total energy.",
       concepts=("geometry_optimization",),
       expected_observation="The energy decreases over successive cycles until it levels off.",
       possible_consequence="Skipping it means later numbers describe an unrelaxed guess.",
       misconceptions=("opt_is_cosmetic",),
       checkpoint=True, questions=("q_opt_predict", "q_opt_why")),
    _S("r3_energies",
       why="Comparing the first and last energy shows what the optimisation actually did.",
       concepts=("molecular_energy", "geometry_optimization"),
       expected_observation="The last energy is lower than the first.",
       misconceptions=("neg_energy_unstable", "opt_is_cosmetic"),
       checkpoint=True, questions=("q_energy_lower", "q_opt_observe", "q_opt_why")),
    _S("p1_open_opt",
       why="The optimised structure is the lowest-energy geometry, so it is the right starting point for the orbital calculation.",
       concepts=("optimized_geometry", "single_point"),
       possible_consequence="Orbital energies from the unrelaxed drawing would not describe the relaxed molecule.",
       checkpoint=True, questions=("q_geom_use_opt", "q_opt_consequence")),
    _S("p2_single_point",
       why="A single point computes the electronic energy and orbitals without moving the atoms again.",
       concepts=("single_point",)),
    _S("p5_homo_lumo",
       why="The HOMO and LUMO are the frontier orbitals: the highest filled and lowest empty.",
       concepts=("homo", "lumo", "molecular_orbitals"),
       misconceptions=("homo_most_electrons",),
       checkpoint=True, questions=("q_homo_meaning",)),
    _S("v3_render_homo",
       why="The picture shows where the HOMO has amplitude across the molecule.",
       concepts=("molecular_orbitals", "homo"),
       expected_observation="Coloured lobes spread over the molecule.",
       misconceptions=("homo_most_electrons",),
       checkpoint=True, questions=("q_orbital_predict", "q_homo_picture")),
    _S("x4_spin",
       why="O2 has an even number of electrons but is not a closed-shell singlet, so charge and spin must be set deliberately.",
       concepts=("electronic_structure",),
       checkpoint=True, questions=("q_electronic_o2",)),
    _S("t1_set",
       why="Each method and basis set is a different approximation of the same molecule.",
       concepts=("method_comparison", "functional", "basis_set"),
       misconceptions=("basis_is_new_molecule", "methods_must_agree"),
       checkpoint=True, questions=("q_method_why", "q_basis_same")),
    _S("t3_orbitals",
       why="Comparing the same quantity across runs shows how much it depends on the approximation.",
       concepts=("interpreting_results", "method_comparison", "homo", "lumo"),
       misconceptions=("methods_must_agree",),
       checkpoint=True, questions=("q_pattern_interpret",)),
    _S("t4_shells",
       why="The s, p, d and f electron counts show which atomic orbitals the occupied orbitals are built from.",
       concepts=("orbital_contribution", "atomic_orbitals"),
       checkpoint=True, questions=("q_contrib_meaning",)),
)

ASSESSMENT = (
    "q_opt_why", "q_geom_use_opt", "q_homo_meaning", "q_homo_picture",
    "q_method_why", "q_contrib_meaning", "q_compare_ch4_o2",
    "q_transfer_opt", "q_transfer_orbitals",
)

KNOWLEDGE = build("exp07", CONCEPTS, STEPS, MISCONCEPTIONS, QUESTIONS, ASSESSMENT)
